name: ${NAME}
version: ${VERSION}
api-version: ${MINECRAFT_VERSION}
main: ru.joutak.plugin.WebStatsPlugin
description: 'A plugin for WebStats of kills'
authors: ['aaalvas']
contributors: []
website: ${WEBSITE}

depend: []
libraries:
  - 'org.projectlombok:lombok:${LOMBOK_VERSION}'

commands:
  webstats:
    description: WebStats control command
    usage: /webstats <debug | metrics | queue>